name: Working with Artifacts

on:
  workflow_dispatch:

jobs:

  test-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: react-app

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: npm ci

      - name: Unit tests
        run: npm run test

      - name: Build code
        run: npm run build

      - name: Check dist
        run: ls -R dist

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: react-app/dist

  deploy:
    needs: test-build
    runs-on: ubuntu-latest

    steps:

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build

      - name: Show folder structure
        run: ls -R build