name: Checkout Proof

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  run-on:
    runs-on: ubuntu-latest
    steps:
      - name: Print current working directory
        run: |
            echo " Current directory"
             pwd
            echo "Contents of current folder"
             ls -la

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print current working directory
        run: |
            echo "Contents of current folder"
             ls -la

      - name: Count Folder
        run: |
            echo "Number of folDER"
            find . -type d | wc -l
      - name: Finished
        run: echo "Proof captured"
