name: Event Filters and Activity Types

on:
    # pull_request:
    #     types:
    #         - opened
    #     branches: 
    #         - main
    #         - test-pr
    workflow_dispatch:
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenever a pr is opened and the base branch is main"