name: SenseTheLog Test

on:
  push:
  pull_request:

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: react-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  analyze:
    runs-on: ubuntu-latest
    needs: [build]
    if: failure()

    steps:
      - name: Analyze with SenseTheLog
        uses: sensethelog/action@v1
        with:
          sensethelog-api-key: ${{ secrets.SENSETHELOG_API_KEY }}